J-Quants/jquants-api-client-python

pyproject.toml, src/jquants-api-client/dummy.py
- initial code to build package to generate PyPI  API token
=> feat: pypi API token preparation

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/ISSUE_TEMPLATE/question.yaml
- add ISSUE_TEMPLATE
- bug report
- feature request
- question
Fixes #6
=> feat: add ISSUE_TEMPLATE

Makefile, README.md, jquantsapi/client.py, poetry.lock, pyproject.toml, tests/test_client.py
- support auth_user API endpoint
- support toml configuration file and environment variables for credentials
fixes #20
=> feat: support auth_ user API endpoint

jquantsapi/client.py
- change parameter data type of get_statements_range
ref. #22
=> feat: unified interfaces improvements

jquantsapi/client.py
- support concurrent fetch for fin statements
- current implementation of get_statements_range takes time to finish
=> feat: support concurrent fetch for fin statements

README.md, jquantsapi/__init__.py, jquantsapi/client.py, jquantsapi/enums.py, tests/test_client.py
- support markets/trades_spec API endpoint
Fixes #28
=> feat: support markets/trades_spec

.github/workflows/build.yml, .github/workflows/publish.yml
- update python version of workflow into 3.11
- python 3.11 released
=> chore(workflow): update python version

.github/workflows/build.yml, .github/workflows/publish.yml, README.md, jquantsapi/client.py
- add get_indices_topix
Fixes #33
=> feat: support index endpoint

examples/20220825-001-price-movement.ipynb, examples/20220825-002-sector.ipynb
- fix example notebooks for v0.2.0 changes
Fixes #37
=> fix: fix example notebooks for v0.2.0 part1

jquantsapi/client.py
- removed temp code to fix a key error
fixes #45 #40
=> fix: remove a temp code to fix a key error

pyproject.toml
- adjust pandas and numpy version requirements
fixes #47
=> fix: fix lib dependencies

.github/workflows/build.yml, jquantsapi/__init__.py, jquantsapi/client.py, jquantsapi/constants.py, tests/test_client.py
- add raw data interfaces
- move column definition into constants
- would like to access raw json string
=> feat: add raw data interfaces

.github/workflows/build.yml, .github/workflows/publish.yml
- update workflow for GitHub Actions 
- bump versions
- fix https://github.com/J-Quants/jquants-api-client-python/issues/54
=> feat: update workflow

poetry.lock, pyproject.toml
- fix numpy version for colab
- an error in colab
=> feat: fix numpy version

jquantsapi/client.py, jquantsapi/constants.py
- add weekly margin interest
- https://github.com/J-Quants/jquants-api-client-python/issues/64
=> feat: add weekly margin interest

jquantsapi/client.py
エラーメッセージについて出し方をrequestsのフォーマットに整える
requestsのフォーマットに整えるため
=> エラーメッセージの修正

jquantsapi/client.py
get_prices_daily_quotes()のDate列をdatetime型になるように修正
Closes #71
=> fix datetime type in get_prices_daily_quotes

jquantsapi/client.py
=> add pagination_key

jquantsapi/client.py, jquantsapi/constants.py
取引カレンダー取得メソッドを追加
取引カレンダーAPI追加予定への対応
=> 取引カレンダーAPI追加

jquantsapi/client.py
prices_amのメソッド修正
データ取得時間外に利用した際にキーエラーが発生するため
=> fix prices_am

jquantsapi/client.py, jquantsapi/constants.py
Indices APIの追加対応
Indices APIが追加になったため
=> indices API追加

jquantsapi/constants.py
財務情報APIにカラムを追加
四半期開示見直しによってカラムが追加されたための対応
=> Add column to Fins Statesments API

README.md, jquantsapi/client.py, jquantsapi/constants.py
空売り残高報告APIの追加に伴い、client.pyへメソッドを追加
=> add Outstanding Short Selling Positions Reported
